openapi: 3.0.1
info:
  title: Keyphrase Extraction API
  description: API to detect keyphrases in text.
  version: 0.2.0

servers:
- url: /

paths:
  /kpe/{lang}:
    post:
      tags:
      - Keyphrase Extraction API
      summary: Perform Keyphrase Extraction
      parameters:
        - name: lang
          in: path
          required: true
          description: Language
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/request'
      responses:
        200:
          description: "Job successfully finished"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/responsemodel'
        400:
          description: "Bad request"
        500:
          description: "Server error"
        
components:
  schemas:
    article:
      type: object
      properties:
        text:
          type: string
          default: This is an article.
    request:
      type: object
      properties:
        articles:
          type: array
          required: true
          items:
            $ref: '#/components/schemas/article'
        component_cfg:
          type: object

    keyphrase:
      type: object
      properties:
        text:
          type: string
        score:
          type: float
    batch:
      type: object
      properties:
        text:
          type: string
        keyphrases:
          type: array
          items:
            $ref: '#/components/schemas/keyphrase'
    
    responsemodel:
      type: object
      properties:
        kpe:
          type: array
          items:
            $ref: '#/components/schemas/batch'
        